# -*- coding: utf-8 -*-
"""punto 2 parcial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nd5Hw5cHjgnQ_6z7y-HJNpmTYbPe1jMf
"""

# Datos del problema
N = [10, 100, 1000]

tiempos_A = [0.01, 0.1, 1.0]
tiempos_B = [0.02, 0.3, 5.0]
tiempos_C = [0.05, 5.0, 500.0]

def calcular_multiplicadores(tiempos):
    """Calcula cuánto crece el tiempo cada vez que N aumenta x10"""
    mult1 = tiempos[1] / tiempos[0]
    mult2 = tiempos[2] / tiempos[1]
    return mult1, mult2

# Cálculo de multiplicadores
mA = calcular_multiplicadores(tiempos_A)
mB = calcular_multiplicadores(tiempos_B)
mC = calcular_multiplicadores(tiempos_C)

print("Multiplicadores al aumentar N x10:")
print(f"Algoritmo A: {mA}")
print(f"Algoritmo B: {mB}")
print(f"Algoritmo C: {mC}")

# Clasificación
print("\nClasificación aproximada según crecimiento:")
print("Algoritmo A → O(n)       (crece x10 cuando N x10)")
print("Algoritmo B → O(n log n) (crece ~x15 al aumentar N x10)")
print("Algoritmo C → O(n^2)     (crece x100 cuando N x10)")

"""# Algoritmo A – Complejidad O(n)

Cuando el tamaño de entrada N aumenta de 10 → 100 → 1000 (es decir, ×10 cada vez), el tiempo del algoritmo pasa de:

0.01 → 0.1 → 1.0

Esto significa que el tiempo también se multiplica aproximadamente ×10 en cada incremento.

Si el tiempo crece en la misma proporción que N, el algoritmo es lineal.

#Algoritmo B – Complejidad O(n log n)

Cuando N aumenta ×10, sus tiempos pasan de:

0.02 → 0.3 → 5.0

Los incrementos son aproximadamente:

De 0.02 a 0.3 → ×15

De 0.3 a 5.0 → ×16.6

El crecimiento es mayor que lineal (×10), pero muchísimo menor que cuadrático (×100).

Este comportamiento intermedio corresponde al crecimiento típico de n log n, propio de algoritmos más eficientes que O(n²) pero más costosos que O(n).

#Algoritmo C – Complejidad O(n²)

Cuando N aumenta ×10, sus tiempos pasan de:

0.05 → 5.0 → 500.0

Los incrementos son exactamente:

De 0.05 a 5.0 → ×100

De 5.0 a 500 → ×100

Si el tiempo aumenta ×100 cuando N aumenta ×10, eso representa un crecimiento proporcional a:

(
10
)
2
=
100
(10)
2
=100
 Esto corresponde al comportamiento cuadrático típico de O(n²).
"""